### PR TITLE
WIP: Add support for supervised learning

### PR DESCRIPTION
**Pull request by ericphanson**
I'm interested trying out UMAP.jl with labelled data. This fits nicely with the new `transform` functionality because you can fit UMAP with labeled data, then add further unlabelled data into the embedding and see where it falls. I'm not sure how this fits into the refactoring plans [you mentioned](https://github.com/dillondaudert/UMAP.jl/issues/27#issuecomment-629397112), so I totally understand if you don't want PRs before you refactor, but I figured I'd put this PR up as a place for discussion. The first commit provides a quick fix for #27 (though again, maybe you want to go a different route).

I've tried to mimic the python version for supporting categorical data. It seems like a really cool feature of UMAP that you can just intersect the fuzzy simplicial complexes, and might be useful for more than just categorical data, so maybe this should be part of a more general approach. It seems like you could in general have `n` points, each with some number of pieces of data (a vector, a label, etc), and a metric for each type of data, and then do UMAP by constructing the fuzzy simplicial complexes for each and then intersecting them. (I don't quite know how this is different than just using a metric on the hetergenous data that is a function of the metrics on each type of data, though. Maybe one difference is that with the define-a-single-hetergenous-metric way, I'm not sure you can really do the "fit with labelled, then transform with unlabelled data" thing).

I think there must be a bug in my implementation, as simple as it is, however, since I get different results than the Python version: I seem to get more points that aren't categorized at all and instead thrown in the middle (hence the "WIP"). So I'm opening this partly in the hope that you might see the difference or spot the bug. I've included some plots below (and the code to generate these plots is in `examples/MNIST_demo.jl`). In trying to debug that and compare the implementations more closely, I noticed that in the Python implementation, here

https://github.com/lmcinnes/umap/blob/b2b6b3085e865273198fd3b0b41fef40d33d2e0e/umap/umap_.py#L287

they seem to pass a iterations parameter to their `nndescent` function. I'm not 100% sure when this code path is hit, but it looks like they scale the number of `nndescent` iterations logarithmically with the size of the data, whereas UMAP.jl fixes it to the NearestNeighborDescent.jl default of 10. So I added a way to pass keyword arguments to the `NearestNeighborDescent.nndescent` call to try to be able to match parameters. That didn't seem to help, unfortunately.

MNIST_jl_unsup_vs_supervised
MNIST_py_unsup_vs_supervised
MNIST_py_vs_jl_supervised
MNIST_py_vs_jl_unsupervised

### CODE REVIEW

**Comment by dillondaudert** [comment]
Thanks for the PR! To your first point, I do think this should wait until the refactoring is finished before merging because the implementation details are sure to look different. I intend to make some significant progress over this weekend, so you hopefully won't have to wait too long. 

At a high level glance, this implementation looks more or less correct - I'll take a more detailed look once we get an updated PR post-refactoring. As for the points in the supervised example that float around outside of the clusters, I don't have an answer yet but it could be due to the quality of the approximate nearest neighbors. There are notable differences between pynndescent and NearestNeighborDescent.jl, most prominently the lack of RP trees for initialization in the Julia version. It could be the Python version does slightly better in this instance, leading to fewer of these un-clustered points (though I do see some).

There's definitely a more generic way to approach embedding heterogeneous data. In the paper, the process is as you describe: construct fuzzy simplicial sets for each combination of (feature, metric) and take the intersection, but I'm also unsure of the difference between this approach and creating a sort of unioned metric that takes a point as a collection of heterogeneous features and returns a single number. I'd be interested in if @lmcinnes has thoughts on that. 

Another potentially useful feature is supporting missing features generically; I'm not sure if, from UMAP's perspective, the "target" variable needs to be treated specially in this regard, but I haven't thought it through fully yet.

**Comment by ericphanson** [comment]
Sounds good! Are you thinking about adding RP initialization to NearestNeighborDescent.jl btw? I might be able to take a look at that next week if it would help (I'm not completely sure if other priorities will come up for me but if not I could spend some time on it).

**Comment by dillondaudert** [comment]
I don't have any immediate plans to add it, no. RP trees aren't as generic (the proofs in the paper for their nice properties only apply to vectors in R^n), and the benefits seemed marginal enough that I never prioritized finishing the implementation. 
I did do some benchmarking to compare the recall of NearestNeighborDescent.jl to pynndescent a long time ago, and I remember the results being somewhat peculiar.

**Comment by dillondaudert** [comment]
I have no objection to supporting RP tree initialization if you do implement them, it would be nice to have the option.

**Comment by ericphanson** [comment]
Closing in favor of https://github.com/dillondaudert/UMAP.jl/pull/36

**Pull request closed without merging**
